## GLOSARIO ##

In [2]:
# List examples

# Append
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)  # Output: [1, 2, 3, 4]

# Extend
my_list = [1, 2, 3]
my_list.extend([4, 5])
print(my_list)  # Output: [1, 2, 3, 4, 5]

# Insert
my_list = [1, 2, 3]
my_list.insert(1, 'hello')
print(my_list)  # Output: [1, 'hello', 2, 3]

# Remove
my_list = [1, 2, 3, 2]
my_list.remove(2)
print(my_list)  # Output: [1, 3, 2]

# Pop
my_list = [1, 2, 3]
popped_element = my_list.pop(1)
print(popped_element)  # Output: 2
print(my_list)  # Output: [1, 3]

# Index
my_list = [1, 2, 3, 2]
print(my_list.index(2))  # Output: 1

# Count
my_list = [1, 2, 3, 2]
print(my_list.count(2))  # Output: 2

# Sort
my_list = [3, 1, 2]
my_list.sort()
print(my_list)  # Output: [1, 2, 3]

# Reverse
my_list = [1, 2, 3]
my_list.reverse()
print(my_list)  # Output: [3, 2, 1]


# Dictionary examples

# Get
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict.get('a'))  # Output: 1
print(my_dict.get('d', 'default value'))  # Output: 'default value'

# Keys
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict.keys())  # Output: ['a', 'b', 'c']

# Values
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict.values())  # Output: [1, 2, 3]

# Items
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict.items())  # Output: [('a', 1), ('b', 2), ('c', 3)]


# Tuples examples

# Creating a tuple
my_tuple = (1, 2, 3)
print(my_tuple)  # Output: (1, 2, 3)

# Accessing elements
print(my_tuple[1])  # Output: 2

# Converting list to tuple
my_list = [1, 2, 3]
my_tuple = tuple(my_list)
print(my_tuple)  # Output: (1, 2, 3)


# Numpy examples

import numpy as np

# Creating a 1D numpy array
my_array = np.array([1, 2, 3])
print(my_array)  # Output: [1 2 3]

# Creating a 2D numpy array
my_array = np.array([[1, 2], [3, 4]])
print(my_array)  # Output: [[1 2]
               
# List examples (continued)

# Slicing
my_list = [1, 2, 3, 4, 5]
print(my_list[1:3])  # Output: [2, 3]

# List comprehension
my_list = [1, 2, 3, 4, 5]
new_list = [x**2 for x in my_list if x % 2 == 0]
print(new_list)  # Output: [4, 16]

# Map
my_list = [1, 2, 3]
new_list = list(map(lambda x: x**2, my_list))
print(new_list)  # Output: [1, 4, 9]

# Filter
my_list = [1, 2, 3, 4, 5]
new_list = list(filter(lambda x: x % 2 == 0, my_list))
print(new_list)  # Output: [2, 4]


# Dictionary examples (continued)

# Pop
my_dict = {'a': 1, 'b': 2, 'c': 3}
popped_value = my_dict.pop('b')
print(popped_value)  # Output: 2
print(my_dict)  # Output: {'a': 1, 'c': 3}

# Update
my_dict1 = {'a': 1, 'b': 2}
my_dict2 = {'b': 3, 'c': 4}
my_dict1.update(my_dict2)
print(my_dict1)  # Output: {'a': 1, 'b': 3, 'c': 4}


# Tuple examples (continued)

# Unpacking
my_tuple = (1, 2, 3)
a, b, c = my_tuple
print(a)  # Output: 1
print(b)  # Output: 2
print(c)  # Output: 3


# Numpy examples (continued)

# Reshaping
my_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = np.reshape(my_array, (2, 3))
print(reshaped_array)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Transpose
my_array = np.array([[1, 2], [3, 4]])
transposed_array = np.transpose(my_array)
print(transposed_array)
# Output:
# [[1 3]
#  [2 4]]

# Concatenation
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = np.concatenate((array1, array2), axis=0)
print(concatenated_array)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Element-wise multiplication
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
product_array = np.multiply(array1, array2)
print(product_array)
# Output:
# [[ 5 12]
#  [21 32]]


[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 'hello', 2, 3]
[1, 3, 2]
2
[1, 3]
1
2
[1, 2, 3]
[3, 2, 1]
1
default value
dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])
(1, 2, 3)
2
(1, 2, 3)
[1 2 3]
[[1 2]
 [3 4]]
[2, 3]
[4, 16]
[1, 4, 9]
[2, 4]
2
{'a': 1, 'c': 3}
{'a': 1, 'b': 3, 'c': 4}
1
2
3
[[1 2 3]
 [4 5 6]]
[[1 3]
 [2 4]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
